### ISSUE TITLE
Job approval on skill modification

### ISSUE THREAD

**Issue by TheNCuber** [scg-unibe-ch/ese2018-team7#2]
Currently if any skill on a job posting is modified, the job is still approved and no further approval by the administrator has to be done. This should be fixed, such that any modification requires approval by the admin.

**Comment by fadnincx** [comment]
Fixed ;)

**Comment by TheNCuber** [comment]
shouldn't a simple removal of a skill require a re-approval as well ?
I think we need to reopen this issue 🤣

**Comment by fadnincx** [comment]
Should (hopefully) be fixed now...
