### ISSUE TITLE
Reload page on admin/mod creation/deletition

### ISSUE THREAD

**Issue by TheNCuber** [scg-unibe-ch/ese2018-team7#6]
In my opinion the usersEdit page should be reloaded when a new mod/admin is created / deleted, such that the new users shows up in the table immediately after creation. With suspension and activation this is already the case and should be a minor fix. Maybe this has something to do with the difference between http PUT and POST.
![image](https://user-images.githubusercontent.com/33098853/47572017-4001f200-d93a-11e8-952d-1ebe7a5f6a7e.png)

**Comment by fadnincx** [comment]
In my option the table should refresh, since the data-source array is updated on that event...

**Comment by TheNCuber** [comment]
It's true that the array is updated, the mat-table however only loads it's data from the specified dataSource (= array) synchronously (e.g on page load), unless you implement complicated subscription logic, and manually call a function on every possible update (add, delete, etc.). That's why I think reloading the page would be a more elagant why of solving this, especially if the user is prompted with a confirmation message before.
